In [17]:
import requests
import pandas as pd
import numpy as np
import gmaps
from config import gkey
import json
from pprint import pprint

gmaps.configure(api_key = gkey)

In [42]:
path = "../Output_Data/Weather_data.csv"

weather_df = pd.DataFrame(pd.read_csv(path))

weather_df

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Busselton,AU,-33.65,115.33,61.00,90,80,13.22
1,1,Erenhot,CN,43.65,111.98,25.29,54,100,13.65
2,2,Rikitea,PF,-23.12,-134.97,77.45,82,1,15.61
3,3,Puerto Ayora,EC,-0.74,-90.35,86.00,70,20,9.17
4,4,Laas,IT,46.62,10.70,48.20,86,0,3.36
...,...,...,...,...,...,...,...,...,...
555,555,Vila do Maio,CV,15.13,-23.22,78.80,39,0,17.22
556,556,Enshi,CN,30.30,109.48,43.47,95,100,2.10
557,557,Rapid Valley,US,44.06,-103.15,66.20,19,20,5.82
558,558,Tucupita,VE,9.06,-62.05,83.08,56,84,7.29
559,559,Omsukchan,RU,62.53,155.80,-5.57,98,100,11.27

In [52]:
lat_lng = []
humid = []

for index, row in weather_df.iterrows():
    
    if row["Humidity"] >= 85:
    
        lat_lng.append((row["Lat"], row["Lng"]))
                                        
# Plot Heatmap
figure_layout = {
    'width': '1000px',
    'height': '750px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)

fig.add_layer(gmaps.heatmap_layer(lat_lng))
fig

Figure(layout=FigureLayout(border='1px solid black', height='750px', margin='0 auto 0 auto', padding='1px', wi…

In [19]:
weather_df = weather_df.loc[weather_df['Max Temp'] < 80]
weather_df = weather_df.loc[weather_df['Max Temp'] > 70]
weather_df = weather_df.loc[weather_df['Wind Speed'] < 10]
weather_df = weather_df.loc[weather_df['Cloudiness'] == 0]

weather_df.head()

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
15,15,Carnarvon,AU,-24.87,113.63,71.60,100,0,3.36
30,30,Beloha,MG,-25.17,45.05,71.38,92,0,8.50
46,46,Salalah,OM,17.02,54.09,75.20,50,0,4.70
76,76,Atar,MR,20.52,-13.05,71.94,7,0,6.51
81,81,Castro,BR,-24.79,-50.01,72.82,63,0,2.82

In [37]:
geocords = []

for index, row in weather_df.iterrows():
    
    geocords.append((row["Lat"], row["Lng"]))
                                        
print(geocords)

[(-24.87, 113.63), (-25.17, 45.05), (17.02, 54.09), (20.52, -13.05), (-24.79, -50.01), (-7.84, -79.15), (20.5, -10.07), (21.43, 39.83), (-23.86, 35.38), (-7.02, 113.87), (9.29, 105.72), (-20.73, 139.5), (-43.3, -65.1), (-24.7, 44.75), (-21.67, 45.17), (20.45, 76.93)]

In [38]:
# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
hotels = []
city = []
country = []

for cord in geocords:
    
    # Parameters dictionary
    params = {
        "location": cord,
        "keyword": "hotel",
        "radius": 5000,
        "type": "hotel",
        "key": gkey
    }

    # run a request using our params dictionary
    response = requests.get(base_url, params=params).json()

    hotels.append(response['results'][0]['name'])
    print(hotels)

#     pprint(json.dumps(response,indent=4,sort_keys=True))

('{\n'
 '    "html_attributions": [],\n'
 '    "results": [],\n'
 '    "status": "INVALID_REQUEST"\n'
 '}')

In [53]:
# Plot Heatmap
figure_layout = {
    'width': '1000px',
    'height': '750px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)

fig.add_layer(gmaps.heatmap_layer(lat_lng))


# Assign the marker layer to a variable
markers = gmaps.marker_layer(geocords)
# Add the layer to the map
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(border='1px solid black', height='750px', margin='0 auto 0 auto', padding='1px', wi…